require: rubocop-rspec
Metrics/MethodLength:
          Max: 25
Metrics/ClassLength:
          Max: 125
Metrics/AbcSize:
          Max: 20
Metrics/CyclomaticComplexity:
          Severity: warning
Style/MutableConstant:
          Enabled: false
