require: rubocop-rspec
AllCops:
          TargetRubyVersion: 2.3
Metrics/MethodLength:
          Max: 25
Metrics/ClassLength:
          Max: 140
Metrics/BlockLength:
        Exclude:
            - 'spec/**/*'
Metrics/AbcSize:
          Max: 21
Metrics/CyclomaticComplexity:
          Severity: warning
Metrics/PerceivedComplexity:
          Max: 8
Style/MutableConstant:
          Enabled: false
RSpec/ExampleLength:
        Max: 21
RSpec/MultipleExpectations:
        Max: 3
